#服务配置
server:
    port: 10060
    servlet:
        # 项目contextPath
        context-path: /best-houseing
    tomcat:
        # tomcat的URI编码
        uri-encoding: UTF-8
        # tomcat最大线程数，默认为200
        max-threads: 800
        # Tomcat启动初始化的线程数，默认值25
        min-spare-threads: 30

# 数据源配置
spring:
    datasource:
        c3p0:
            # 主库数据源
            master:
                driverClass: com.mysql.jdbc.Driver
                jdbcUrl: jdbc:mysql://10.10.8.22:3306/mcdb?useUnicode=true&characterEncoding=utf-8&tinyInt1isBit=false&useSSL=false&allowMultiQueries=true
                user: mtmydb
                password: '@mtmydb'
                initialPoolSize: 5
                minPoolSize: 5
                maxPoolSize: 50
                acquireIncrement: 5
                acquireRetryAttempts: 30
                acquireRetryDelay: 1000
                maxIdleTime: 120
                maxConnectionAge: 0
                maxStatements: 100
                maxStatementsPerConnection: 5
                preferredTestQuery: SELECT SYSDATE() FROM DUAL
                idleConnectionTestPeriod: 120
                numHelperThreads: 3
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                driverClass: com.mysql.jdbc.Driver
                jdbcUrl: jdbc:mysql://10.10.8.22:3306/mcdb?useUnicode=true&characterEncoding=utf-8&tinyInt1isBit=false&useSSL=false&allowMultiQueries=true
                user: mtmydb
                password: '@mtmydb'
                initialPoolSize: 5
                minPoolSize: 5
                maxPoolSize: 50
                acquireIncrement: 5
                acquireRetryAttempts: 30
                acquireRetryDelay: 1000
                maxIdleTime: 120
                maxConnectionAge: 0
                maxStatements: 100
                maxStatementsPerConnection: 5
                preferredTestQuery: SELECT SYSDATE() FROM DUAL
                idleConnectionTestPeriod: 120
                numHelperThreads: 3
